import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'hi' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'ur';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// A core translation dictionary for key UI texts
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.foodScanner': 'Food Scanner',
    'nav.medicineScanner': 'Medicine Scanner',
    'nav.smartPantry': 'Smart Pantry',
    'nav.aiInsights': 'AI Insights',
    'nav.aiAssistant': 'AI Assistant',
    'nav.settings': 'Settings',
    'nav.logout': 'Log Out',
    
    // Auth & General
    'auth.login': 'Log In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Full Name',
    'auth.remember': 'Remember Me',
    'auth.forgot': 'Forgot Password?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.demoLogin': 'Demo Login',
    'auth.useDemo': 'Use Demo Account',
    'auth.createAccount': 'Create Account',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile Information',
    'settings.theme': 'Appearance Theme',
    'settings.language': 'Selected Language',
    'settings.save': 'Save Changes',
    'settings.privacy': 'Privacy & Security',
    'settings.notifications': 'Notifications Config',
    'settings.light': 'Light Mode',
    'settings.dark': 'Dark Mode',
    
    // Fallbacks & common
    'common.loading': 'Loading...',
    'common.tryAgain': 'Try Again',
    'common.scanNow': 'Scan Now',
    'common.viewDetails': 'View Details',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.add': 'Add',
    
    // Page Header Defaults
    'header.dashboard': 'Health & Fitness Dashboard',
    'header.foodScanner': 'Food Nutrition Scanner',
    'header.medicineScanner': 'Medicine Label Scanner',
    'header.smartPantry': 'Smart Kitchen Pantry',
    'header.aiInsights': 'Personal AI Insights',
    'header.aiAssistant': 'Personal AI Health Companion',
  },
  es: {
    // Navigation
    'nav.dashboard': 'Panel de Control',
    'nav.foodScanner': 'Escáner de Alimentos',
    'nav.medicineScanner': 'Escáner de Medicinas',
    'nav.smartPantry': 'Despensa Inteligente',
    'nav.aiInsights': 'Análisis IA',
    'nav.aiAssistant': 'Asistente IA',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    
    // Auth & General
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.name': 'Nombre Completo',
    'auth.remember': 'Recordarme',
    'auth.forgot': '¿Olvidó su contraseña?',
    'auth.dontHaveAccount': '¿No tienes una cuenta de acceso?',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.demoLogin': 'Acceso de Demostración',
    'auth.useDemo': 'Usar Cuenta Demo',
    'auth.createAccount': 'Crear Cuenta',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.profile': 'Información del Perfil',
    'settings.theme': 'Tema de Apariencia',
    'settings.language': 'Idioma Seleccionado',
    'settings.save': 'Guardar Cambios',
    'settings.privacy': 'Privacidad y Seguridad',
    'settings.notifications': 'Configuración de Notificaciones',
    'settings.light': 'Modo Claro',
    'settings.dark': 'Modo Oscuro',
    
    // Fallbacks & common
    'common.loading': 'Cargando...',
    'common.tryAgain': 'Reintentar',
    'common.scanNow': 'Escanear Ahora',
    'common.viewDetails': 'Ver Detalles',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.add': 'Añadir',
    
    // Page Header Defaults
    'header.dashboard': 'Panel de Salud y Bienestar',
    'header.foodScanner': 'Escáner de Nutrición Alimentos',
    'header.medicineScanner': 'Escáner de Etiquetas de Medicina',
    'header.smartPantry': 'Despensa Inteligente de Cocina',
    'header.aiInsights': 'Análisis Personal de IA',
    'header.aiAssistant': 'Compañero Personal de Salud IA',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.foodScanner': 'Scanner Aliments',
    'nav.medicineScanner': 'Scanner Médicaments',
    'nav.smartPantry': 'Garde-Manger',
    'nav.aiInsights': 'Analyses IA',
    'nav.aiAssistant': 'Assistant IA',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    
    // Auth & General
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'Adresse E-mail',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.name': 'Nom complet',
    'auth.remember': 'Se souvenir de moi',
    'auth.forgot': 'Mot de passe oublié ?',
    'auth.dontHaveAccount': "Vous n'avez pas de compte ?",
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte ?',
    'auth.demoLogin': 'Connexion Démo',
    'auth.useDemo': 'Utiliser le compte Démo',
    'auth.createAccount': 'Créer un compte',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.profile': 'Informations de Profil',
    'settings.theme': "Thème d'Apparence",
    'settings.language': 'Langue Sélectionnée',
    'settings.save': 'Enregistrer',
    'settings.privacy': 'Confidentialité & Sécurité',
    'settings.notifications': 'Configuration des Notifications',
    'settings.light': 'Mode Clair',
    'settings.dark': 'Mode Sombre',
    
    // Fallbacks & common
    'common.loading': 'Chargement...',
    'common.tryAgain': 'Réessayer',
    'common.scanNow': 'Scanner Maintenant',
    'common.viewDetails': 'Voir Détails',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.add': 'Ajouter',
    
    // Page Header Defaults
    'header.dashboard': 'Tableau de Bord Santé',
    'header.foodScanner': 'Scanner de Nutrition Alimentaire',
    'header.medicineScanner': 'Scanner d\'Étiq Médicaments',
    'header.smartPantry': 'Garde-Manger Intelligent',
    'header.aiInsights': 'Analyses Santé Personnel',
    'header.aiAssistant': 'Compagnon de Santé IA',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.foodScanner': 'खाद्य स्कैनर',
    'nav.medicineScanner': 'दवा स्कैनर',
    'nav.smartPantry': 'स्मार्ट रसोई',
    'nav.aiInsights': 'एआई विमर्श',
    'nav.aiAssistant': 'एआई सहायक',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'लॉग आउट',
    
    'auth.login': 'लॉग इन करें',
    'auth.signup': 'साइन अप करें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.name': 'पूरा नाम',
    'auth.remember': 'मुझे याद रखें',
    'auth.forgot': 'पासवर्ड भूल गए?',
    'auth.dontHaveAccount': 'खाता नहीं है?',
    'auth.alreadyHaveAccount': 'पहले से ही एक खाता है?',
    'auth.demoLogin': 'डेमो लॉग इन',
    'auth.useDemo': 'डेमो खाते का उपयोग करें',
    'auth.createAccount': 'खाता बनाएं',
    
    'settings.title': 'सेटिंग्स',
    'settings.profile': 'प्रोफ़ाइल जानकारी',
    'settings.theme': 'रूप-रंग थीम',
    'settings.language': 'चयनित भाषा',
    'settings.save': 'परिवर्तन सहेजें',
    'settings.privacy': 'गोपनीयता और सुरक्षा',
    'settings.notifications': 'अधिसूचना विन्यास',
    'settings.light': 'लाइट मोड',
    'settings.dark': 'डार्क मोड',
    
    'common.loading': 'लोड हो रहा है...',
    'common.tryAgain': 'पुनः प्रयास करें',
    'common.scanNow': 'अभी स्कैन करें',
    'common.viewDetails': 'विवरण देखें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.add': 'जोड़ें',
    
    'header.dashboard': 'स्वास्थ्य और फिटनेस डैशबोर्ड',
    'header.foodScanner': 'खाद्य पोषण स्कैनर',
    'header.medicineScanner': 'दवा लेबल स्कैनर',
    'header.smartPantry': 'स्मार्ट रसोई भंडार',
    'header.aiInsights': 'व्यक्तिगत एआई विमर्श',
    'header.aiAssistant': 'व्यक्तिगत एआई स्वास्थ्य साथी',
  },
  bn: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.foodScanner': 'খাদ্য স্ক্যানার',
    'nav.medicineScanner': 'ওষুধ স্ক্যানার',
    'nav.smartPantry': 'স্মার্ট রান্নাঘর',
    'nav.aiInsights': 'এআই ইনসাইটস',
    'nav.aiAssistant': 'এআই সহকারী',
    'nav.settings': 'সেটিংস',
    'nav.logout': 'লগ আউট',
    
    'auth.login': 'লগ ইন',
    'auth.signup': 'সাইন আপ',
    'auth.email': 'ইমেল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.name': 'সম্পূর্ণ নাম',
    'auth.remember': 'মনে রাখুন',
    'auth.forgot': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.dontHaveAccount': 'অ্যাকাউন্ট নেই?',
    'auth.alreadyHaveAccount': 'ইতিমধ্যেই অ্যাকাউন্ট আছে?',
    'auth.demoLogin': 'ডেমো লগইন',
    'auth.useDemo': 'ডেমো অ্যাকাউন্ট ব্যবহার করুন',
    'auth.createAccount': 'অ্যাকাউন্ট তৈরি করুন',
    
    'settings.title': 'সেটিংস',
    'settings.profile': 'প্রোফাইল তথ্য',
    'settings.theme': 'পছন্দসই থিম',
    'settings.language': 'নির্বাচিত ভাষা',
    'settings.save': 'তথ্য সংরক্ষণ',
    'settings.privacy': 'গোপনীয়তা ও নিরাপত্তা',
    'settings.notifications': 'বিজ্ঞপ্তি কনফিগারেশন',
    'settings.light': 'লাইট মোড',
    'settings.dark': 'ডার্ক মোড',
    
    'common.loading': 'লোড হচ্ছে...',
    'common.tryAgain': 'আবার চেষ্টা করুন',
    'common.scanNow': 'এখনই স্ক্যান করুন',
    'common.viewDetails': 'বিস্তারিত দেখুন',
    'common.cancel': 'বাতিল',
    'common.save': 'সংরক্ষণ',
    'common.add': 'যুক্ত করুন',
    
    'header.dashboard': 'স্বাস্থ্য ও ফিটনেস ড্যাশবোর্ড',
    'header.foodScanner': 'খাদ্য পুষ্টি স্ক্যানার',
    'header.medicineScanner': 'ওষুধ লেবেল স্ক্যানার',
    'header.smartPantry': 'স্মার্ট রান্নাঘরের ভাণ্ডার',
    'header.aiInsights': 'ব্যক্তিগত এআই তথ্য',
    'header.aiAssistant': 'ব্যক্তিগত এআই স্বাস্থ্য সঙ্গী',
  },
  ta: {
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.foodScanner': 'உணவு ஸ்கேனர்',
    'nav.medicineScanner': 'மருந்து ஸ்கேனர்',
    'nav.smartPantry': 'ஸ்மார்ட் சமையலறை',
    'nav.aiInsights': 'ஏஐ நுண்ணறிவு',
    'nav.aiAssistant': 'ஏஐ உதவியாளர்',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',
    
    'auth.login': 'உள்நுழை',
    'auth.signup': 'பதிவுசெய்',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்துக',
    'auth.name': 'முழு பெயர்',
    'auth.remember': 'என்னை நினைவில் கொள்',
    'auth.forgot': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'auth.dontHaveAccount': 'கணக்கு இல்லையா?',
    'auth.alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.demoLogin': 'டெமோ உள்நுழைவு',
    'auth.useDemo': 'டெமோ கணக்கைப் பயன்படுத்துக',
    'auth.createAccount': 'கணக்கை உருவாக்கு',
    
    'settings.title': 'அமைப்புகள்',
    'settings.profile': 'சுயவிவரத் தகவல்',
    'settings.theme': 'அமைப்பின் தீம்',
    'settings.language': 'தேர்ந்தெடுக்கப்பட்ட மொழி',
    'settings.save': 'மாற்றங்களைச் சேமி',
    'settings.privacy': 'தனியுரிமை மற்றும் பாதுகாப்பு',
    'settings.notifications': 'அறிவிப்பு உள்ளமைப்பு',
    'settings.light': 'ஒளி பயன்முறை',
    'settings.dark': 'இருண்ட பயன்முறை',
    
    'common.loading': 'ஏற்றப்படுகிறது...',
    'common.tryAgain': 'மீண்டும் முயற்சிசெய்',
    'common.scanNow': 'இப்போது ஸ்கேன் செய்',
    'common.viewDetails': 'விவரங்களைக் காண்க',
    'common.cancel': 'ரத்துசெய்',
    'common.save': 'சேமி',
    'common.add': 'சேர்',
    
    'header.dashboard': 'சுகாதாரம் மற்றும் உடற்பயிற்சி டாஷ்போர்டு',
    'header.foodScanner': 'உணவு ஊட்டச்சத்து ஸ்கேனர்',
    'header.medicineScanner': 'மருந்து லேபிள் ஸ்கேனர்',
    'header.smartPantry': 'ஸ்மார்ட் சமையலறை களஞ்சியம்',
    'header.aiInsights': 'தனிப்பட்ட ஏஐ நுண்ணறிவுத் தரவு',
    'header.aiAssistant': 'தனிப்பட்ட ஏஐ சுகாதாரத் துணைவி',
  },
  te: {
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.foodScanner': 'ఆహార స్కానర్',
    'nav.medicineScanner': 'మందుల స్కానర్',
    'nav.smartPantry': 'స్మార్ట్ వంటగది',
    'nav.aiInsights': 'ఏఐ అంతర్దృష్టులు',
    'nav.aiAssistant': 'ఏఐ సహాయకుడు',
    'nav.settings': 'సెట్టింగ్స్',
    'nav.logout': 'లాగ్ అవుట్',
    
    'auth.login': 'లాగిన్',
    'auth.signup': 'సైన్ అప్',
    'auth.email': 'ఈమెయిల్ చిరునామా',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.confirmPassword': 'పాస్‌వర్డ్ ధృవీకరించు',
    'auth.name': 'పూర్తి పేరు',
    'auth.remember': 'నన్ను గుర్తుంచుకో',
    'auth.forgot': 'పాస్‌వర్డ్ మరిచిపోయారా?',
    'auth.dontHaveAccount': 'ఖాతా లేదా?',
    'auth.alreadyHaveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
    'auth.demoLogin': 'డెమో లాగిన్',
    'auth.useDemo': 'డెమో ఖాతాను ఉపయోగించు',
    'auth.createAccount': 'ఖాతాను సృష్టించు',
    
    'settings.title': 'సెట్టింగ్స్',
    'settings.profile': 'ప్రొఫైల్ సమాచారం',
    'settings.theme': 'రూపకల్పన థీమ్',
    'settings.language': 'ఎంచుకున్న భాష',
    'settings.save': 'మార్పులను సేవ్ చేయి',
    'settings.privacy': 'గోప్యత & భద్రత',
    'settings.notifications': 'నోటిఫికేషన్ కాన్ఫిగరేషన్',
    'settings.light': 'లైట్ మోడ్',
    'settings.dark': 'డార్క్ మోడ్',
    
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.tryAgain': 'మళ్ళీ ప్రయత్నించు',
    'common.scanNow': 'ఇప్పుడే స్కాన్ చేయి',
    'common.viewDetails': 'వివరాలు చూడు',
    'common.cancel': 'రద్దు చేయి',
    'common.save': 'సేవ్ చేయి',
    'common.add': 'జోడించు',
    
    'header.dashboard': 'ఆరోగ్యం & ఫిట్‌నెస్ డ్యాష్‌బోర్డ్',
    'header.foodScanner': 'ఆహార పోషక విలువల స్కానర్',
    'header.medicineScanner': 'మందుల లేబుల్ స్కానర్',
    'header.smartPantry': 'స్మార్ట్ కిచెన్ ప్యాంట్రీ',
    'header.aiInsights': 'వ్యక్తిగత ఏఐ అంతర్దృష్టులు',
    'header.aiAssistant': 'వ్యక్తిగత ఏఐ ఆరోగ్య సహచరుడు',
  },
  mr: {
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.foodScanner': 'अन्न स्कॅनर',
    'nav.medicineScanner': 'औषध स्कॅनर',
    'nav.smartPantry': 'स्मार्ट स्वयंपाकघर',
    'nav.aiInsights': 'एआय इनसाइट्स',
    'nav.aiAssistant': 'एआय सहाय्यक',
    'nav.settings': 'सेटिंग्ज',
    'nav.logout': 'लॉग आउट',
    
    'auth.login': 'लॉग इन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.confirmPassword': 'पासवर्डची पुष्टी करा',
    'auth.name': 'पूर्ण नाव',
    'auth.remember': 'माझी आठवण ठेवा',
    'auth.forgot': 'पासवर्ड विसरलात?',
    'auth.dontHaveAccount': 'खाते नाही?',
    'auth.alreadyHaveAccount': 'आधीच खाते आहे का?',
    'auth.demoLogin': 'डेमो लॉगिन',
    'auth.useDemo': 'डेमो खाते वापरा',
    'auth.createAccount': 'खाते तयार करा',
    
    'settings.title': 'सेटिंग्ज',
    'settings.profile': 'प्रोफाइल माहिती',
    'settings.theme': 'स्वरूप थीम',
    'settings.language': 'निवडलेली भाषा',
    'settings.save': 'बदल जतन करा',
    'settings.privacy': 'गोपनीयता आणि सुरक्षा',
    'settings.notifications': 'अधिसूचना गोपनीयता',
    'settings.light': 'लाइट मोड',
    'settings.dark': 'डार्क मोड',
    
    'common.loading': 'लोड होत आहे...',
    'common.tryAgain': 'पुन्हा प्रयत्न करा',
    'common.scanNow': 'आता स्कॅन करा',
    'common.viewDetails': 'तपशील पहा',
    'common.cancel': 'रद्द करा',
    'common.save': 'जतन करा',
    'common.add': 'जोडा',
    
    'header.dashboard': 'आरोग्य आणि फिटनेस डॅशबोर्ड',
    'header.foodScanner': 'अन्न पोषण स्कॅनर',
    'header.medicineScanner': 'औषध लेबल स्कॅनर',
    'header.smartPantry': 'स्मार्ट किचन पॅन्ट्री',
    'header.aiInsights': 'वैयक्तिक एआय विमर्श',
    'header.aiAssistant': 'वैयक्तिक एआय आरोग्य सोबती',
  },
  gu: {
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.foodScanner': 'ખોરાક સ્કેનર',
    'nav.medicineScanner': 'દવા સ્કેનર',
    'nav.smartPantry': 'સ્માર્ટ રસોડું',
    'nav.aiInsights': 'એઆઈ ઇનસાઇટ્સ',
    'nav.aiAssistant': 'એઆઈ સહાયક',
    'nav.settings': 'સેટિંગ્સ',
    'nav.logout': 'લૉગ આઉટ',
    
    'auth.login': 'લૉગ ઇન',
    'auth.signup': 'સાઇન અપ',
    'auth.email': 'ઇમેઇલ સરનામું',
    'auth.password': 'પાસવર્ડ',
    'auth.confirmPassword': 'પાસવર્ડ કન્ફર્મ કરો',
    'auth.name': 'પૂરું નામ',
    'auth.remember': 'મને યાદ રાખો',
    'auth.forgot': 'પાસવર્ડ ભૂલી ગયા છો?',
    'auth.dontHaveAccount': 'ખાતું નથી?',
    'auth.alreadyHaveAccount': 'પહેલેથી જ ખાતું છે?',
    'auth.demoLogin': 'ડેમો લૉગિન',
    'auth.useDemo': 'ડેમો એકાઉન્ટ વાપરો',
    'auth.createAccount': 'ખાતું બનાવો',
    
    'settings.title': 'સેટિંગ્સ',
    'settings.profile': 'પ્રોફાઇલ માહિતી',
    'settings.theme': 'દેખાવ થીમ',
    'settings.language': 'પસંદ કરેલી ભાષા',
    'settings.save': 'ફેરફારો સાચવો',
    'settings.privacy': 'ગોપનીયતા અને સુરક્ષા',
    'settings.notifications': 'સૂચના રૂપરેખાંકન',
    'settings.light': 'લાઇટ મોડ',
    'settings.dark': 'ડાર્ક મોડ',
    
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.tryAgain': 'ફરીથી પ્રયાસ કરો',
    'common.scanNow': 'હમણાં સ્કેન કરો',
    'common.viewDetails': 'વિગતો જુઓ',
    'common.cancel': 'રદ કરો',
    'common.save': 'સાચવો',
    'common.add': 'ઉમેરો',
    
    'header.dashboard': 'આરોગ્ય અને ફિટનેસ ડેશબોર્ડ',
    'header.foodScanner': 'ખોરાક પોષણ સ્કેનર',
    'header.medicineScanner': 'દવા લેબલ સ્કેનર',
    'header.smartPantry': 'સ્માર્ટ કિચન પેન્ટ્રી',
    'header.aiInsights': 'વ્યક્તિગત એઆઈ વિગતો',
    'header.aiAssistant': 'વྱક્તિગત એઆઈ આરોગ્ય સાથીદાર',
  },
  kn: {
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌',
    'nav.foodScanner': 'ಆಹಾರ ಸ್ಕ್ಯಾನರ್‌',
    'nav.medicineScanner': 'ಔಷಧ ಸ್ಕ್ಯಾನರ್‌',
    'nav.smartPantry': 'ಸ್ಮಾರ್ಟ್ ಅಡುಗೆಮನೆ',
    'nav.aiInsights': 'ಎಐ ಒಳನೋಟಗಳು',
    'nav.aiAssistant': 'ಎಐ ಸಹಾಯಕ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    
    'auth.login': 'ಲಾಗ್ ಇನ್',
    'auth.signup': 'ಸೈನ್ ಅಪ್',
    'auth.email': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.confirmPassword': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'auth.name': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.remember': 'ನನ್ನನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಿ',
    'auth.forgot': 'ಪಾಸ್‌ವರ್ಡ್ ಮುರಿದುಹೋಗಿದೆಯೇ?',
    'auth.dontHaveAccount': 'ಖಾತೆ ಹೊಂದಿಲ್ಲವೇ?',
    'auth.alreadyHaveAccount': 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?',
    'auth.demoLogin': 'ಡೆಮೊ ಲಾಗಿನ್',
    'auth.useDemo': 'ಡೆಮೊ ಖಾತೆ ಬಳಸಿ',
    'auth.createAccount': 'ಖಾತೆ ರಚಿಸಿ',
    
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
    'settings.profile': 'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ',
    'settings.theme': 'ಅಲಂಕಾರದ ಥೀಮ್',
    'settings.language': 'ಆಯ್ದ ಭಾಷೆ',
    'settings.save': 'ಬದಲಾವಣೆ ಉಳಿಸಿ',
    'settings.privacy': 'ಗೌಪ್ಯತೆ ಮತ್ತು ರಕ್ಷಣೆ',
    'settings.notifications': 'ಅಧಿಸೂಚನೆ ಕಾನ್ಫಿಗರೇಶನ್',
    'settings.light': 'ಬೆಳಕಿನ ಮೋಡ್',
    'settings.dark': 'ಡಾರ್ಕ್ ಮೋಡ್',
    
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.tryAgain': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'common.scanNow': 'ಈಗಲೇ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'common.viewDetails': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.add': 'ಸೇರಿಸಿ',
    
    'header.dashboard': 'ಆರೋಗ್ಯ ಮತ್ತು ಫಿಟ್‌ನೆಸ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'header.foodScanner': 'ಆಹಾರ ಪೌಷ್ಟಿಕಾಂಶ ಸ್ಕ್ಯಾನರ್',
    'header.medicineScanner': 'ಔಷಧ ಲೇಬಲ್ ಸ್ಕ್ಯಾನರ್',
    'header.smartPantry': 'ಸ್ಮಾರ್ಟ್ ಅಡುಗೆ ಯಾರ್ಡ್',
    'header.aiInsights': 'ವೈಯಕ್ತಿಕ ಎಐ ಒಳನೋಟಗಳು',
    'header.aiAssistant': 'ವೈಯಕ್ತಿಕ ಎಐ ಆರೋಗ್ಯ ಸಹಚರ',
  },
  ml: {
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.foodScanner': 'ഭക്ഷണ സ്കാനർ',
    'nav.medicineScanner': 'മരുന്ന് സ്കാനർ',
    'nav.smartPantry': 'സ്മാർട്ട് അടുക്കള',
    'nav.aiInsights': 'എഐ സ്ഥിതിവിവരങ്ങൾ',
    'nav.aiAssistant': 'എഐ സഹായി',
    'nav.settings': 'സെറ്റിംഗ്സ്',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    
    'auth.login': 'ലോഗ് ഇൻ',
    'auth.signup': 'സൈൻ അപ്പ്',
    'auth.email': 'ഇമെയിൽ വിലാസം',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.confirmPassword': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'auth.name': 'പൂർണ്ണമായ പേര്',
    'auth.remember': 'ഓർമ്മിക്കുക',
    'auth.forgot': 'പാസ്‌വേഡ് മറന്നുപോയോ?',
    'auth.dontHaveAccount': 'അക്കൗണ്ട് ഇല്ലേ?',
    'auth.alreadyHaveAccount': 'നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ?',
    'auth.demoLogin': 'ഡെമോ ലോഗിൻ',
    'auth.useDemo': 'ഡെമോ അക്കൗണ്ട് ഉപയോഗിക്കുക',
    'auth.createAccount': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    
    'settings.title': 'സെറ്റിംഗ്സ്',
    'settings.profile': 'പ്രൊഫൈൽ വിവരങ്ങൾ',
    'settings.theme': 'രൂപകൽപ്പന തീം',
    'settings.language': 'തിരഞ്ഞെടുത്ത ഭാഷ',
    'settings.save': 'മാറ്റങ്ങൾ സൂക്ഷിക്കുക',
    'settings.privacy': 'സ്വകാര്യതയും സുരക്ഷയും',
    'settings.notifications': 'അറിയിപ്പ് കോൺഫിഗറേഷൻ',
    'settings.light': 'ലൈറ്റ് മോഡ്',
    'settings.dark': 'ഡാർക്ക് മോഡ്',
    
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.tryAgain': 'വീണ്ടും ശ്രമിക്കുക',
    'common.scanNow': 'ഇപ്പോൾ സ്കാൻ ചെയ്യുക',
    'common.viewDetails': 'വിവരങ്ങൾ കാണുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.save': 'സൂക്ഷിക്കുക',
    'common.add': 'ചേർക്കുക',
    
    'header.dashboard': 'ആരോഗ്യ ഫിറ്റ്നസ് ഡാഷ്‌ബോർഡ്',
    'header.foodScanner': 'ഭക്ഷണ പോഷകാഹാര സ്കാനർ',
    'header.medicineScanner': 'മരുന്ന് ലേബൽ സ്കാനർ',
    'header.smartPantry': 'സ്മാർട്ട് അടുക്കള കാബിനറ്റ്',
    'header.aiInsights': 'വ്യക്തിഗത എഐ സ്ഥിതിവിവരങ്ങൾ',
    'header.aiAssistant': 'വ്യക്തിഗത എഐ ആരോഗ്യ പങ്കാളി',
  },
  pa: {
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.foodScanner': 'ਭੋਜਨ ਸਕੈਨਰ',
    'nav.medicineScanner': 'ਦਵਾਈ ਸਕੈਨਰ',
    'nav.smartPantry': 'ਸਮਾਰਟ ਰਸੋਈ',
    'nav.aiInsights': 'ਏਆਈ ਇਨਸਾਈਟਸ',
    'nav.aiAssistant': 'ਏਆਈ ਸਹਾਇਕ',
    'nav.settings': 'ਸੈਟਿੰਗਜ਼',
    'nav.logout': 'ਲੌਗ ਆਉਟ',
    
    'auth.login': 'ਲੌਗ ਇਨ',
    'auth.signup': 'ਸਾਈਨ ਅਪ',
    'auth.email': 'ਈਮੇਲ ਪਤਾ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.confirmPassword': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'auth.name': 'ਪੂਰਾ ਨਾਮ',
    'auth.remember': 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
    'auth.forgot': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    'auth.dontHaveAccount': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    'auth.alreadyHaveAccount': 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
    'auth.demoLogin': 'ਡੇਮੋ ਲੌਗਿਨ',
    'auth.useDemo': 'ਡੇਮੋ ਖਾਤਾ ਵਰਤੋਂ',
    'auth.createAccount': 'ਖਾਤਾ ਬਣਾਓ',
    
    'settings.title': 'ਸੈਟਿੰਗਜ਼',
    'settings.profile': 'ਪ੍ਰੋਫਾਈਲ ਜਾਣਕਾਰੀ',
    'settings.theme': 'ਦਿੱਖ ਥੀਮ',
    'settings.language': 'ਚੁਣੀ ਗਈ ਭਾਸ਼ਾ',
    'settings.save': 'ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    'settings.privacy': 'ਪ੍ਰਾਈਵੇਸੀ ਅਤੇ ਸੁਰੱਖਿਆ',
    'settings.notifications': 'ਨੋਟੀਫਿਕੇਸ਼ਨ ਸੈਟਿੰਗਜ਼',
    'settings.light': 'ਲਾਈਟ ਮੋਡ',
    'settings.dark': 'ਡਾਰਕ ਮੋਡ',
    
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.tryAgain': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'common.scanNow': 'ਹੁਣੇ ਸਕੈਨ ਕਰੋ',
    'common.viewDetails': 'ਵੇਰਵੇ ਦੇਖੋ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.save': 'ਸੁਰੱਖਿਅਤ ਕਰੋ',
    'common.add': 'ਜੋੜੋ',
    
    'header.dashboard': 'ਸਿਹਤ ਅਤੇ ਫਿਟਨੈਸ ਡੈਸ਼ਬੋਰਡ',
    'header.foodScanner': 'ਭੋਜਨ ਪੋਸ਼ਣ ਸਕੈനਰ',
    'header.medicineScanner': 'ਦਵਾਈ ਲੇਬਰ ਸਕੈਨਰ',
    'header.smartPantry': 'ਸਮਾਰਟ ਰਸੋਈ ਪੈਂਟਰੀ',
    'header.aiInsights': 'ਨਿੱਜੀ ਏਆਈ ਜਾਣਕਾਰੀ',
    'header.aiAssistant': 'ਨਿੱਜੀ ਏਆਈ ਸਿਹਤ ਸਾਥੀ',
  },
  ur: {
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.foodScanner': 'غذائی اسکینر',
    'nav.medicineScanner': 'ادویات کا اسکینر',
    'nav.smartPantry': 'اسمارٹ باورچی خانہ',
    'nav.aiInsights': 'اے آئی بصیرت',
    'nav.aiAssistant': 'اے آئی مددگار',
    'nav.settings': 'ترتیبات',
    'nav.logout': 'لاگ آؤٹ',
    
    'auth.login': 'لاگ ان',
    'auth.signup': 'سائن اپ',
    'auth.email': 'ای میل کا پتہ',
    'auth.password': 'پاس ورڈ',
    'auth.confirmPassword': 'پاس ورڈ کی تصدیق کریں',
    'auth.name': 'مکمل نام',
    'auth.remember': 'مجھے یاد رکھیں',
    'auth.forgot': 'پاس ورڈ بھول گئے؟',
    'auth.dontHaveAccount': 'اکاؤنٹ نہیں ہے؟',
    'auth.alreadyHaveAccount': 'پہلے سے اکاؤنٹ ہے؟',
    'auth.demoLogin': 'ڈیمو لاگ ان',
    'auth.useDemo': 'ڈیمو اکاؤنٹ استعمال کریں',
    'auth.createAccount': 'اکاؤنٹ بنائیں',
    
    'settings.title': 'ترتیبات',
    'settings.profile': 'پروفائل کی معلومات',
    'settings.theme': 'تھیم کا انتخاب',
    'settings.language': 'منتخب کردہ زبان',
    'settings.save': 'تبدیلیاں محفوظ کریں',
    'settings.privacy': 'رازداری اور سیکیورٹی',
    'settings.notifications': 'نوٹیفکیشن کی ترتیبات',
    'settings.light': 'لائٹ موڈ',
    'settings.dark': 'ڈارک موڈ',
    
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.tryAgain': 'دوبارہ کوشش کریں',
    'common.scanNow': 'ابھی اسکین کریں',
    'common.viewDetails': 'تفصیلات دیکھیں',
    'common.cancel': 'منسوخ کریں',
    'common.save': 'محفوظ کریں',
    'common.add': 'شامل کریں',
    
    'header.dashboard': 'صحت اور فٹنس ڈیش بورڈ',
    'header.foodScanner': 'غذائی افادیت کا اسکینر',
    'header.medicineScanner': 'میڈیسن لیبل اسکینر',
    'header.smartPantry': 'اسمارٹ کچن پینٹری',
    'header.aiInsights': 'انفرادی اے آئی تجزیہ',
    'header.aiAssistant': 'انفرادی اے آئی صحت کا ساتھی',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('hg_lang');
    const validLangs: string[] = ['en', 'es', 'fr', 'hi', 'bn', 'ta', 'te', 'mr', 'gu', 'kn', 'ml', 'pa', 'ur'];
    if (saved && validLangs.includes(saved)) return saved as Language;
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('hg_lang', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const langDict = translations[language] || translations['en'];
    return langDict[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
